[build]
  command = "npm run build"
  publish = "build"
  functions = "functions-build"

[dev]
  command = "react-scripts start"

[template.environment]
  AUTH0_DOMAIN = "Your Auth0 application domain"
  AUTH0_CLIENT_ID = "Your Auth0 application client id"
  JWKS_URI = "The jwks uri from auth0"
  NEXMO_NEXMO_APP_ID = "Your nexmo application id"
  NEXMO_NEXMO_APP_PRIV_KEY_B64 = "Your nexmo application private key in base64"
  NEXMO_NEXMO_JTW_ISS_NAME = "The issuer field for the nexmo JWT"
